[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#E6B200"
backgroundColor = "#FFF3D1"
secondaryBackgroundColor = "#FFFAF0"
textColor = "#1F2933"
font = "sans serif"
